image: docker:19.03-dind

variables:
  DOCKER_DRIVER: overlay2
  # Create the certificates inside this directory for both the server
  # and client. The certificates used by the client will be created in
  # /certs/client so we only need to share this directory with the
  # volume mount in `config.toml`.
  DOCKER_TLS_CERTDIR: "/certs"
  DEFCONFIG: docker_kvm_rpi3_defconfig

services:
  - docker:19.03.0-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

docker:
  stage: build
  script: 
    - docker build -t registry.gitlab.com/darkmane/rpi64-kernel .
    - docker push registry.gitlab.com/darkmane/rpi64-kernel:latest

kernel:
  stage: build
  script:
    - mkdir builds
    - docker run -e DEFCONFIG=$DEFCONFIG -e BUILD_NR=test -v $(pwd)/builds:/builds --name rpikernelbuilder registry.gitlab.com/darkmane/rpi64-kernel
    - docker rm rpikernelbuilder
  artifacts:
    paths:
      - builds